"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.STEP_ACTIVATED = exports.STEP_ACTIVE = exports.STEP_START = exports.STEP_PREPARE = exports.STEP_NONE = exports.STATUS_LEAVE = exports.STATUS_ENTER = exports.STATUS_APPEAR = exports.STATUS_NONE = void 0;
exports.STATUS_NONE = 'none';
exports.STATUS_APPEAR = 'appear';
exports.STATUS_ENTER = 'enter';
exports.STATUS_LEAVE = 'leave';
exports.STEP_NONE = 'none';
exports.STEP_PREPARE = 'prepare';
exports.STEP_START = 'start';
exports.STEP_ACTIVE = 'active';
exports.STEP_ACTIVATED = 'end';
